import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import * as brand from "../config/brand";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const outfit = Outfit({ subsets: ["latin"], variable: "--font-outfit" });

export const metadata: Metadata = {
  title: brand.APP_NAME,
  description: "Custom PWA generated by DialDeploy",
  manifest: "/manifest.json",
  viewport: "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no",
  themeColor: brand.PRIMARY_COLOR,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="apple-touch-icon" href="/icon-192.png" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
      </head>
      <body className={`${inter.variable} ${outfit.variable} font-sans bg-zinc-950 text-zinc-50 min-h-screen flex flex-col`}>
        <header className="sticky top-0 z-50 border-b border-zinc-800/80 bg-zinc-950/70 backdrop-blur-md px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div 
              className="w-3 h-3 rounded-full animate-pulse" 
              style={{ backgroundColor: brand.PRIMARY_COLOR }}
            />
            <span className="font-heading font-semibold text-lg tracking-tight">
              {brand.HEADER_TITLE}
            </span>
          </div>
        </header>
        
        <main className="flex-1 max-w-md w-full mx-auto p-4 pb-24 flex flex-col">
          {children}
        </main>
        
        {/* Service Worker Registration */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if ('serviceWorker' in navigator) {
                window.addEventListener('load', function() {
                  navigator.serviceWorker.register('/sw.js').then(function(reg) {
                    console.log('SW registered:', reg.scope);
                  }, function(err) {
                    console.log('SW reg failed:', err);
                  });
                });
              }
            `,
          }}
        />
      </body>
    </html>
  );
}
